apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-tomcat-app
  labels:
    app: java-tomcat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-tomcat-app
  template:
    metadata:
      labels:
        app: java-tomcat-app
    spec:
      containers:
        - name: java-tomcat-container
          image: apoorvad4/java-tomcat-app:latest   
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
