apiVersion: v1
kind: Service
metadata:
  name: java-tomcat-app
  labels:
    app: java-tomcat-app
spec:
  selector:
    app: java-tomcat-app
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8080
      nodePort: 30080
